#!/bin/bash

pki_dir=/etc/icinga2/pki
fqdn=`hostname -f`
icinga2_master=ip-172-31-9-220.us-west-2.compute.internal
icinga2_master_port=5665
ticket=`curl -k -s -u root:2d726aed7210c73d -H 'Accept: application/json' -X POST 'https://ip-172-31-9-220.us-west-2.compute.internal:5665/v1/actions/generate-ticket' -d '{ "cn": "'$fqdn'" }' | awk '{print $4}' | awk -F\' '{print $2}'`


mkdir $pki_dir; chmod 0700 $pki_dir; chown icinga:icinga $pki_dir
icinga2 pki new-cert --cn $fqdn --key $pki_dir/$fqdn.key --cert $pki_dir/$fqdn.crt
icinga2 pki save-cert --key $pki_dir/$fqdn.key --cert $pki_dir/$fqdn.crt --trustedcert $pki_dir/trusted-master.crt --host $icinga2_master
icinga2 pki request --host $icinga2_master --port $icinga2_master_port --ticket $ticket --key $pki_dir/$fqdn.key --cert $pki_dir/$fqdn.crt --trustedcert $pki_dir/trusted-master.crt --ca $pki_dir/ca.key
icinga2 node setup --ticket $ticket --endpoint $icinga2_master --zone $fqdn --master_host $icinga2_master --trustedcert $pki_dir/trusted-master.crt
icinga2 feature enable command


####Configure zones
cat >/etc/icinga2/zones.conf << EOFZONECONF
/*
* Generated by Icinga 2 node setup commands
*/

object Endpoint "$icinga2_master" {
host = "$icinga2_master"
port = "5665"
}

object Zone "master" {
endpoints = [ "$icinga2_master" ]
}

object Endpoint NodeName {
}

object Zone ZoneName {
endpoints = [ NodeName ]
parent = "master"
}
EOFZONECONF


service icinga2 restart



systemctl restart icinga2  # or however you restart your icinga
