---
- name: Enable Icinga
  service:
    name: icinga2
    enabled: yes
    state: started

- name: Enable MariaDB
  service:
    name: mariadb
    enabled: yes
    state: started

- name: Enable HTTPD
  service:
    name: httpd
    enabled: yes
    state: started
